### ISSUE TITLE
FindProjectByProjectGuid issue

### ISSUE THREAD

**Issue by krombipils** [themotleyfool/SlimJim#6]
Hi,

I really like SlimJim. It greatly improved my development process.
Unfortunately I noticed a problem on a new Solution today:
In one of my .csproj files another project is referenced as

{21a04d4a-9152-4e90-9570-4380eda479b4}

while the project guid in the referenced project is

{21A04D4A-9152-4E90-9570-4380EDA479B4}

Because SlnBuilder.FindProjectByProjectGuid uses an '==' comparison, this project is not included in the generated sln. I changed the code to 

return projectsList.Find(csp => string.Equals(csp.Guid, projectGuid, StringComparison.OrdinalIgnoreCase));

and now it is fine.

**Comment by jazzdev** [comment]
I ran into this too. I think it's better to upcase the guids when loading the
projects because FindProjectByProjectGuid is not the only place in the code
where guids are compared.

**Comment by chriseldredge** [comment]
Fixed by #10.
